[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "msp430-rtfm"
version = "0.1.0"

[dependencies]
static-ref = "0.2.0"
msp430 = "0.1.0"

[dependencies.msp430-rtfm-macros]
path = "macros"
